# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-24 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tag',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
