# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-24 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20161024_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(through='blog.BlogTag', to='blog.Tag'),
        ),
    ]
