# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-10 15:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Course'),
        ),
    ]
