# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-24 02:17
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=64, primary_key=True, serialize=False, verbose_name='Activation key'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=64, primary_key=True, serialize=False, verbose_name='Activation key'),
        ),
    ]
